import { AnimatePresence, motion } from 'framer-motion';
import { UserRound, ArrowUpRight, X } from 'lucide-react';
import SceneLayout from '../components/SceneLayout';
import CharacterPortrait from '../components/CharacterPortrait';
import GameButton from '../components/GameButton';
import Diamond from '../components/Diamond';
import { characters } from '../data/storyData';
export default function CharactersScene({state,dispatch}) {
  const profile=characters.find(c=>c.id===state.profile);
  return <SceneLayout eyebrow="THE PEOPLE BEHIND THE COMPANY" title="MEET THE CHARACTERS" className="characters-scene"><p className="scene-caption">Select a character to open their profile.</p><div className="character-grid">{characters.map((c,i)=><motion.button initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.35,delay:i*.08}} whileHover={{y:-7,scale:1.015}} whileTap={{scale:.98}} className={`character-card panel ${c.id} ${profile?.id===c.id ? "selected" : profile ? "dimmed" : ""}`} key={c.id} onClick={()=>dispatch({type:'PROFILE',id:c.id})}><span className="character-number">0{i+1}</span>{profile?.id===c.id&&<motion.span className="selected-marker" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}}><Diamond/></motion.span>}<div className="portrait-disc"/><CharacterPortrait id={c.id}/><div className="character-card-copy"><span className="role-label"><UserRound size={18}/> CHARACTER PROFILE</span><h2>{c.name}</h2><p>Played by <strong>{c.actor}</strong></p><span className="profile-link">VIEW PROFILE <ArrowUpRight size={20}/></span></div></motion.button>)}</div><AnimatePresence>{profile&&<motion.div className="profile-overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} role="dialog" aria-modal="true" aria-labelledby="profile-title" onKeyDown={e=>{if(e.key==='Tab'){e.preventDefault();e.currentTarget.querySelector('button').focus();}}}><motion.div className={`profile-detail panel ${profile.id}`} initial={{scale:.94,y:20}} animate={{scale:1,y:0}}><button autoFocus className="icon-button profile-close" aria-label="Close profile" onClick={()=>dispatch({type:'PROFILE',id:null})}><X/></button><div className="profile-visual"><CharacterPortrait id={profile.id}/></div><div className="profile-copy"><span className="eyebrow">CHARACTER PROFILE</span><h2 id="profile-title">{profile.name}</h2><p className="played-by">Played by <strong>{profile.actor}</strong></p><h3>ROLE</h3><p>{profile.role}</p>{profile.background&&<p className="character-fact">{profile.background}</p>}<GameButton onClick={()=>dispatch({type:'PROFILE',id:null})}>{state.sideVisit?'BACK TO CHARACTERS':'BACK TO GAME'}</GameButton></div></motion.div></motion.div>}</AnimatePresence></SceneLayout>;
}

