import { motion, AnimatePresence } from 'framer-motion';
import { useEffect, useState } from 'react';
import { BriefcaseBusiness, MessageCircle, CircleHelp, AlertTriangle, Users, Minus } from 'lucide-react';
import SceneLayout from '../components/SceneLayout';
import SystemAlert from '../components/SystemAlert';
import StatusPanel from '../components/StatusPanel';
import DialogueBox from '../components/DialogueBox';
import CharacterPortrait from '../components/CharacterPortrait';
import Diamond from '../components/Diamond';
import { assets, story, employees } from '../data/storyData';

export default function HookScene(){return <SceneLayout className="hook-scene"><SystemAlert><div className="hook-topline"><span>FIRST IMPRESSIONS</span><span>EXECUTIVE COMMITTEE</span></div><div className="na-mystery">N/A</div><p className="alert-subtitle">Missing evaluation records detected.</p><p className="welcome-line">{story.welcome}</p><div className="hook-question"><MessageCircle/><h1>{story.hook}</h1></div><div className="discussion-label">OPEN FLOOR <span/> Take a moment. Share your first reaction.</div></SystemAlert></SceneLayout>;}

export function CompanyScene({dispatch}){const [entering,setEntering]=useState(false); const enter=()=>{if(entering)return; console.log('Building clicked'); setEntering(true); try{setTimeout(()=>{console.log('Navigating to private-conversation');dispatch({type:'NEXT'});},650);}catch(error){console.error('Building transition failed',error);setEntering(false);dispatch({type:'NEXT'});}};useEffect(()=>{const listener=()=>enter();window.addEventListener("enter-headquarters",listener);return()=>window.removeEventListener("enter-headquarters",listener);},[entering]);return <SceneLayout eyebrow="MAIN QUEST 01" title="ENTER THE COMPANY" className="company-scene"><div className={`company-grid ${entering?"hq-entering":""}`}><div className="company-visual"><div className="company-halo"/><motion.div className="hq-model" animate={entering?{scale:1.18,y:-28,rotateY:0,filter:"brightness(1.08)"}:{rotateY:[-4,4,-4],scale:[1,1.01,1]}} transition={entering?{duration:.65,ease:"easeInOut"}:{duration:10,repeat:Infinity,ease:"easeInOut"}} whileHover={entering?undefined:{scale:1.03,filter:"brightness(1.08)"}} onClick={enter} role="button" tabIndex={0}><img src={assets.company} alt="Company headquarters"/></motion.div><span className="location-chip"><BriefcaseBusiness size={22}/> COMPANY HEADQUARTERS</span></div><div className="company-info"><section className="panel company-profile"><h2>COMPANY PROFILE</h2>{story.company.map((text,i)=><motion.p key={text} initial={{opacity:0,x:12}} animate={{opacity:1,x:0}} transition={{duration:.35,delay:i*.1}}><span>0{i+1}</span>{text}</motion.p>)}</section><StatusPanel items={story.status}/></div></div><div className="quest-bar panel"><BriefcaseBusiness/><div><span>YOUR ROLE</span><strong>Executive Committee Member</strong></div><div className="quest-objective"><span>OBJECTIVE</span><strong>{story.objective}</strong></div></div></SceneLayout>;}
export function ConversationScene({state,dispatch}){const {step}=state;const line=story.conversation[step===0?0:1];const advance=()=>dispatch({type:'NEXT'});return <SceneLayout eyebrow="" title="" className="conversation-scene"><div className="conversation-hud">04 / 12 · PRIVATE CONVERSATION</div><div className="office-stage" style={{backgroundImage:`linear-gradient(90deg,rgba(12,47,69,.18),rgba(12,47,69,.28)),url(${assets.office})`}}><motion.div className={`conversation-actor actor-ceo ${line.speaker==='ceo'?'active':'inactive'}`} animate={{scale:line.speaker==='ceo'?1.03:.97,opacity:line.speaker==='ceo'?1:.65}} transition={{duration:.25}}><CharacterPortrait id="ceo"/></motion.div><motion.div className={`conversation-actor actor-frank ${line.speaker==='frank'?'active':'inactive'}`} animate={{scale:line.speaker==='frank'?1.03:.97,opacity:line.speaker==='frank'?1:.65}} transition={{duration:.25}}><CharacterPortrait id="frank"/></motion.div><AnimatePresence>{step===0&&<motion.div className="conversation-intro" initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} exit={{opacity:0}} transition={{duration:.3}}>BEHIND CLOSED DOORS</motion.div>}</AnimatePresence><div className="conversation-content"><DialogueBox speaker={line.speaker} text={line.text} onAdvance={advance}/>{step>=2&&<section className="layoff-panel panel"><h2>LAYOFF RULE</h2><ol>{story.rules.slice(0,step-1).map((rule,i)=><motion.li key={rule} initial={{opacity:0,x:15}} animate={{opacity:1,x:0}} transition={{duration:.3}}><span>{i+1}</span>{rule}</motion.li>)}</ol></section>}</div></div></SceneLayout>;}
export function AppraisalScene(){const [detected,setDetected]=useState(0);const [showWarning,setShowWarning]=useState(false);const [showManager,setShowManager]=useState(false);const [showMood,setShowMood]=useState(false);const managerText=story.manager;useEffect(()=>{const timers=[setTimeout(()=>setDetected(1),700),setTimeout(()=>setDetected(2),860),setTimeout(()=>setDetected(3),1020),setTimeout(()=>{setShowWarning(true);setShowManager(true);},1500),setTimeout(()=>setShowMood(true),3850)];return()=>timers.forEach(clearTimeout);},[]);return <SceneLayout eyebrow="PERFORMANCE REVIEW" title="SYSTEM ALERT: N/A DETECTED" className="appraisal-scene"><div className="appraisal-grid"><SystemAlert title="EMPLOYEE APPRAISALS"><table className="appraisal-table"><thead><tr><th>Employee</th><th>Score</th></tr></thead><tbody>{employees.map(([name,score],i)=>{const missing=score===null;const isDetected=missing&&detected>i-5;return <motion.tr key={name} className={isDetected?'missing detected':''} animate={isDetected?{backgroundColor:'#fbe5e2'}:{backgroundColor:'transparent'}} transition={{duration:.35}}><td>{isDetected&&<motion.span initial={{opacity:0,scale:.7}} animate={{opacity:1,scale:1}} className="row-warning"><AlertTriangle size={22}/></motion.span>} {name}</td><td>{missing?(isDetected?<motion.span initial={{opacity:0,color:'#f4f7fa'}} animate={{opacity:1,color:'#d85850',scale:[1,1.08,1]}} transition={{duration:.4}}>{'N/A'}</motion.span>:<span className="na-neutral">N/A</span>):score}</td></motion.tr>;})}</tbody></table>{showWarning&&<motion.p className="missing-alert" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}}><AlertTriangle/>{story.missingAlert}</motion.p>}</SystemAlert><div className="appraisal-reactions">{showManager&&<motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.5,ease:'easeOut'}} className="manager-explains"><div className="manager-head"><CharacterPortrait id="manager"/></div><DialogueBox speaker="manager" text={managerText}/></motion.div>}{showMood&&<motion.div initial={{opacity:0,scale:.94,y:10}} animate={{opacity:1,scale:1,y:0}} transition={{duration:.36,ease:'easeOut'}} className="mood-panel panel"><div className="mood-portrait"><CharacterPortrait id="frank"/></div><div><span className="role-label">FRANK’S MOOD</span><h2>{story.mood}</h2><p>{story.moodStatus}</p></div><CircleHelp size={35}/></motion.div>}</div></div></SceneLayout>;}
export function OfficeScene({state}){const final=state.step===5;const showReaction=state.step===0;return <SceneLayout eyebrow="A DIFFICULT CONVERSATION" title="THE CEO’S OFFICE" className="ceo-office-scene"><div className="office-stage ceo-stage" style={{backgroundImage:`linear-gradient(90deg,rgba(16,53,67,.16),rgba(16,53,67,.2)),url(${assets.ceoOffice})`}}><div className={`office-portrait ${showReaction?'frank-office-character':''}`}>{showReaction&&<><motion.img className="office-negative-plumbob" src={assets.negativePlumbob} alt="" initial={{opacity:0,y:-12,scale:.8}} animate={{opacity:[0,1,1,0],y:[-12,0,-4,4],scale:[.8,1,1,1]}} transition={{duration:1.35,delay:.15}}/><motion.img className="office-relationship-loss" src={assets.relationshipLoss} alt="" initial={{opacity:0,scale:.7,x:8}} animate={{opacity:[0,1,1,0],scale:[.7,1.05,1,1],x:[8,0,-3,0]}} transition={{duration:1.05,delay:.3}}/></>}<CharacterPortrait id={state.step===0?'frank':'ceo'}/></div><div className="office-dialogue"><div className="dialogue-context"><MessageCircle size={22}/>{state.step===0?'FRANK ASKS':'CEO RESPONDS'}<span>{state.step===0?'':`${state.step} / 5`}</span></div><DialogueBox speaker={state.step===0?'frank':'ceo'} text={state.step===0?story.frankQuestion:story.ceoResponses[state.step-1]} significant={final}/>{state.step>1&&<div className="conversation-history">{story.ceoResponses.slice(0,Math.min(state.step-1,4)).map(text=><p key={text}>“{text}”</p>)}</div>}</div></div></SceneLayout>;}

export function DilemmaScene(){return <SceneLayout eyebrow="THREE VALUES. ONE DECISION." title="THE REAL DILEMMA" className="dilemma-scene"><div className="tension-diagram"><svg className="tension-lines" viewBox="0 0 1400 520" aria-hidden="true"><path d="M700 68 240 410 1160 410Z" fill="none" stroke="#c7f5ff" strokeWidth="3" strokeDasharray="8 10"/><path d="M700 68 700 295M240 410 700 295 1160 410" fill="none" stroke="#ffffff55" strokeWidth="2"/></svg>{story.values.map((value,i)=><motion.div initial={{opacity:0,scale:.94}} animate={{opacity:1,scale:1}} transition={{delay:i*.1,duration:.35}} className={`value-card panel value-${i}`} key={value}><Diamond/><h2>{value}</h2></motion.div>)}<div className="tension-center"><CharacterPortrait id="frank"/><span>FRANK</span></div></div><div className="dilemma-question"><MessageCircle/><h2>{story.dilemma}</h2></div></SceneLayout>;}





















